# ---------------------------------
# Bash interactive shell only
# ---------------------------------

# Enable bash completion (macOS/Homebrew)
if [ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]; then
  . /opt/homebrew/etc/profile.d/bash_completion.sh
elif [ -r /usr/local/etc/profile.d/bash_completion.sh ]; then
  . /usr/local/etc/profile.d/bash_completion.sh
fi