# Bash Profile
# Late Update: Mar 15, 2026
[ -f "$HOME/.paths" ] && . "$HOME/.paths"

# rbenv (bash only)
if command -v rbenv >/dev/null; then
  eval "$(rbenv init - bash)"
fi

# GPG
export GPG_TTY=$(tty)
